# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import testbed_pb2 as testbed__pb2


class TestbedStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.FlashImage = channel.unary_unary(
        '/testbed.Testbed/FlashImage',
        request_serializer=testbed__pb2.ImageFlashRequest.SerializeToString,
        response_deserializer=testbed__pb2.ImageFlashReply.FromString,
        )


class TestbedServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def FlashImage(self, request, context):
    """Sends a image flash request
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TestbedServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'FlashImage': grpc.unary_unary_rpc_method_handler(
          servicer.FlashImage,
          request_deserializer=testbed__pb2.ImageFlashRequest.FromString,
          response_serializer=testbed__pb2.ImageFlashReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'testbed.Testbed', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
