# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: testbed.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='testbed.proto',
  package='testbed',
  syntax='proto3',
  serialized_pb=_b('\n\rtestbed.proto\x12\x07testbed\"=\n\x11ImageFlashRequest\x12\x11\n\tfile_path\x18\x01 \x01(\t\x12\x15\n\rserial_number\x18\x02 \x03(\r\"\"\n\x0fImageFlashReply\x12\x0f\n\x07message\x18\x01 \x01(\t2O\n\x07Testbed\x12\x44\n\nFlashImage\x12\x1a.testbed.ImageFlashRequest\x1a\x18.testbed.ImageFlashReply\"\x00\x42,\n\x14io.grpc.test.testbedB\x0cTestDedProtoP\x01\xa2\x02\x03HLWb\x06proto3')
)




_IMAGEFLASHREQUEST = _descriptor.Descriptor(
  name='ImageFlashRequest',
  full_name='testbed.ImageFlashRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='file_path', full_name='testbed.ImageFlashRequest.file_path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='serial_number', full_name='testbed.ImageFlashRequest.serial_number', index=1,
      number=2, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=87,
)


_IMAGEFLASHREPLY = _descriptor.Descriptor(
  name='ImageFlashReply',
  full_name='testbed.ImageFlashReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='testbed.ImageFlashReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=123,
)

DESCRIPTOR.message_types_by_name['ImageFlashRequest'] = _IMAGEFLASHREQUEST
DESCRIPTOR.message_types_by_name['ImageFlashReply'] = _IMAGEFLASHREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ImageFlashRequest = _reflection.GeneratedProtocolMessageType('ImageFlashRequest', (_message.Message,), dict(
  DESCRIPTOR = _IMAGEFLASHREQUEST,
  __module__ = 'testbed_pb2'
  # @@protoc_insertion_point(class_scope:testbed.ImageFlashRequest)
  ))
_sym_db.RegisterMessage(ImageFlashRequest)

ImageFlashReply = _reflection.GeneratedProtocolMessageType('ImageFlashReply', (_message.Message,), dict(
  DESCRIPTOR = _IMAGEFLASHREPLY,
  __module__ = 'testbed_pb2'
  # @@protoc_insertion_point(class_scope:testbed.ImageFlashReply)
  ))
_sym_db.RegisterMessage(ImageFlashReply)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\024io.grpc.test.testbedB\014TestDedProtoP\001\242\002\003HLW'))

_TESTBED = _descriptor.ServiceDescriptor(
  name='Testbed',
  full_name='testbed.Testbed',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=125,
  serialized_end=204,
  methods=[
  _descriptor.MethodDescriptor(
    name='FlashImage',
    full_name='testbed.Testbed.FlashImage',
    index=0,
    containing_service=None,
    input_type=_IMAGEFLASHREQUEST,
    output_type=_IMAGEFLASHREPLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TESTBED)

DESCRIPTOR.services_by_name['Testbed'] = _TESTBED

try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities


  class TestbedStub(object):
    # missing associated documentation comment in .proto file
    pass

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.FlashImage = channel.unary_unary(
          '/testbed.Testbed/FlashImage',
          request_serializer=ImageFlashRequest.SerializeToString,
          response_deserializer=ImageFlashReply.FromString,
          )


  class TestbedServicer(object):
    # missing associated documentation comment in .proto file
    pass

    def FlashImage(self, request, context):
      """Sends a image flash request
      """
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_TestbedServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'FlashImage': grpc.unary_unary_rpc_method_handler(
            servicer.FlashImage,
            request_deserializer=ImageFlashRequest.FromString,
            response_serializer=ImageFlashReply.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'testbed.Testbed', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaTestbedServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def FlashImage(self, request, context):
      """Sends a image flash request
      """
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaTestbedStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def FlashImage(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      """Sends a image flash request
      """
      raise NotImplementedError()
    FlashImage.future = None


  def beta_create_Testbed_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('testbed.Testbed', 'FlashImage'): ImageFlashRequest.FromString,
    }
    response_serializers = {
      ('testbed.Testbed', 'FlashImage'): ImageFlashReply.SerializeToString,
    }
    method_implementations = {
      ('testbed.Testbed', 'FlashImage'): face_utilities.unary_unary_inline(servicer.FlashImage),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_Testbed_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('testbed.Testbed', 'FlashImage'): ImageFlashRequest.SerializeToString,
    }
    response_deserializers = {
      ('testbed.Testbed', 'FlashImage'): ImageFlashReply.FromString,
    }
    cardinalities = {
      'FlashImage': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'testbed.Testbed', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
